matches:
  - trigger: ":must"
    replace: "![must-badge](https://img.shields.io/badge/review-must-critical.svg)"
  - trigger: ":want"
    replace: "![want-badge](https://img.shields.io/badge/review-want-blue)"
  - trigger: ":nits"
    replace: "![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)"
  - trigger: ":typo"
    replace: "![typo-badge](https://img.shields.io/badge/review-typo-orange.svg)"
  - trigger: ":ask"
    replace: "![ask-badge](https://img.shields.io/badge/review-ask-yellow.svg)"
  - trigger: ":imo"
    replace: "![imo-badge](https://img.shields.io/badge/review-imo-green.svg)"
  - trigger: ":next"
    replace: "![next-badge](https://img.shields.io/badge/review-next-skyblue.svg)"
  - trigger: ":good"
    replace: "![good-badge](https://img.shields.io/badge/review-good-success.svg)"
  - trigger: ":memo"
    replace: "![memo-badge](https://img.shields.io/badge/review-memo-lightgrey)"
