matches:
  - trigger: ":a:"
    replace: "alpha"
  - trigger: ":b:"
    replace: "bravo"
  - trigger: ":c:"
    replace: "charlie"
  - trigger: ":d:"
    replace: "delta"
  - trigger: ":e:"
    replace: "echo"
  - trigger: ":f:"
    replace: "foxtrot"
  - trigger: ":g:"
    replace: "golf"
  - trigger: ":h:"
    replace: "hotel"
  - trigger: ":i:"
    replace: "india"
  - trigger: ":j:"
    replace: "juliett"
  - trigger: ":k:"
    replace: "kilo"
  - trigger: ":l:"
    replace: "lima"
  - trigger: ":m:"
    replace: "mike"
  - trigger: ":n:"
    replace: "november"
  - trigger: ":o:"
    replace: "oscar"
  - trigger: ":p:"
    replace: "papa"
  - trigger: ":q:"
    replace: "quebec"
  - trigger: ":r:"
    replace: "romeo"
  - trigger: ":s:"
    replace: "sierra"
  - trigger: ":t:"
    replace: "tango"
  - trigger: ":u:"
    replace: "uniform"
  - trigger: ":v:"
    replace: "victor"
  - trigger: ":w:"
    replace: "whiskey"
  - trigger: ":x:"
    replace: "xray"
  - trigger: ":y:"
    replace: "yankee"
  - trigger: ":z:"
    replace: "zulu"
